#ifndef _AUTONCHOOSER_HPP_
#define _AUTONCHOOSER_HPP_
#define BLUEPOS_FINALS_NOGRAB3RDMOGO -6
#define BLUEPOS_FINALS_GRAB3RDMOGO -5
#define BLUEPOS_TEAMWORK_NOGRAB3RDMOGO -4
#define BLUEPOS_TEAMWORK_GRAB3RDMOGO -3
#define BLUENEG_SIGWP -2
#define BLUENEG_TEAMWORK -1
#define REDNEG_TEAMWORK 1
#define REDNEG_SIGWP 2
#define REDPOS_TEAMWORK_GRAB3RDMOGO 3
#define REDPOS_TEAMWORK_NOGRAB3RDMOGO 4
#define REDPOS_FINALS_GRAB3RDMOGO 5
#define REDPOS_FINALS_NOGRAB3RDMOGO 6
#define SKILLS 7
#define TEST 8
void chooser(int &status);

void run_auton(int selected);

#endif